create table COCKTAIL
(
    ID   UUID PRIMARY KEY,
    ID_DRINK TEXT,
    NAME TEXT,
    INGREDIENTS TEXT
);


create table COCKTAIL_SHOPPING_LIST
(
    COCKTAIL_ID   UUID,
    SHOPPING_LIST_ID UUID,
    PRIMARY KEY (SHOPPING_LIST_ID, COCKTAIL_ID),
    CONSTRAINT FK_COCKTAIL
        FOREIGN KEY(COCKTAIL_ID)
            REFERENCES COCKTAIL(ID),

    CONSTRAINT FK_SHOPPING_LIST
        FOREIGN KEY(SHOPPING_LIST_ID)
            REFERENCES SHOPPING_LIST(ID)
);