/*create table COCKTAIL_SHOPPING_LIST
(
    ID   UUID,
    SHOPPING_LIST_ID UUID,
    CONSTRAINT FK_COCKTAIL_SHOP FOREIGN KEY(ID) REFERENCES COCKTAIL(ID),
    CONSTRAINT FK_COCKTAIL_SHOP2 FOREIGN KEY(SHOPPING_LIST_ID) REFERENCES SHOPPING_LIST(ID)
);
*/